### PR TITLE
Added new article

### PR DESCRIPTION
**Pull request by iAmrSalman**

### CODE REVIEW

**Comment by LisaDziuba** [comment]
hey @iAmrSalman! let's add Judging MVC to the Flawless iOS publication?

Here is how to submit a guide to our blog, Flawless iOS:
https://help.medium.com/hc/en-us/articles/213904978-Add-a-draft-or-post-to-publication

Also, would you mind making it free? This way more people from the community will be able to read it and you will get more attention.

To do so, you just change Distribution settings, by unchecking the box

**Comment by LisaDziuba** [comment]
hey @iAmrSalman! 
I added you as a writer. 

Now you can submit your guide to Flawless iOS :) These are the steps: https://help.medium.com/hc/en-us/articles/213904978-Add-a-draft-or-post-to-publication

**Comment by LisaDziuba** [comment]
@iAmrSalman thanks for sharing your article within Flawless iOS publication 🥳

**Comment by iAmrSalman** [comment]
🎉🎉

**Pull request merged**
